name: Work with Container specifs
on:
  push:
jobs:
  example-docker-compose:
    runs-on: ubuntu-latest
    services:
      wordpress:
        image: wordpress
        restart: always
        ports:
          - 8080:80
        environment:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_USER: deliomed
          WORDPRESS_DB_PASSWORD: dkf9x898983usha0dmk92sX
          WORDPRESS_DB_NAME: wordpress
        volumes:
          - ./wordpress:/var/www/html
          - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

      db:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_DATABASE: wordpress
          MYSQL_USER: deliomed
          MYSQL_PASSWORD: dkf9x898983usha0dmk92sX
          MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
          - ./db:/var/lib/mysql
    steps:
      - name: get init page wordpress
        run: curl http://localhost:8080
