name: Work with containers
on:
  push:
jobs:
  container-docker:
    runs-on: ubuntu-latest
    container:
      image: nginx:latest
    steps:
      - name: nginx docker default version latest
        run: nginx -v

      - name: use nginx docker version 1.20.2
        uses: docker://nginx:1.20.2

      - name: nginx docker version 1.20.2
        run: nginx -v

      
