name: Containers
on:
  push:
jobs:
  jobs-docker:
    runs-on: ubuntu-latest
    steps:
      - name: image nginx and list version
        uses: docker://nginx:latest
        with:
          entrypoint: nginx
          args: -v
      
      - name: image node and list version
        uses: docker://node:lts-alpine3.15
        with:
          entrypoint: node
          args: -v