name: Work with containers
on:
#  push:
  pull_request:
jobs:
  container-docker:
    runs-on: ubuntu-latest
    container:
      image: nginx:latest
    steps:
      - name: nginx docker default version latest
        run: |
          nginx -v
          type nginx

      - name: use nginx docker version 1.20.2
        uses: docker://nginx:1.20.2
        with:
          entrypoint: /usr/sbin/nginx
          args: -v