name: Containers
on:
  push:
jobs:
  jobs-docker:
    runs-on: ubuntu-latest
    steps:
      - name: image nginx
        uses: docker://nginx:latest
      
      - name: List version nxginx
        run: nginx -v

      - name: image node
        uses: docker://node:lts-alpine3.15

      - name: List version node
        run: node -v