name: Work with containers
on:
  push:
jobs:
  container-docker:
    runs-on: ubuntu-latest
    container:
      image: nginx:latest
    steps:
      - name: nginx docker default version latest
        run: nginx -v

      - name: use nginx docker version 1.21.6
        uses: docker://nginx:1.21.6

      - name: nginx docker version 1.21.6
        run: nginx -v

      
