name: Jobs Status
on: [push]

jobs:
  jobs-status-test:
    runs-on: ubuntu-latest
    steps:
      - name: Jobs Failure
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        run:
          node -v

      - name: Sucess
        if: sucess()
        run: |
          echo "Anterior executou com sucesso"
      - name: Failure
        if: always()
        run: |
          echo "Estou sempre executando"