name: Jobs Status
on: [push]

jobs:
  jobs-status-test:
    runs-on: ubuntu-latest
    steps:
      - name : Default node version
        run: node -v

      - name: Change node version
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Success
        if: success()
        run: |
          eccho "Anterior executou com sucesso"
          node -v

      - name: Failure
        if: failure()
        run: |
          echo "Estou sempre executando mesmo em falha"